clear; close all; clc

samples = 4095;

poly1   = [12    10         5         0];
poly2   = [12         8         3 2   0];

init    = [0 0 0 0 0 0 0 0 0 0 0 1];
mask    = [0 0 0 0 0 0 0 0 0 0 0 1];

pnSequence1 = comm.PNSequence(...
    'Polynomial',               poly1,	...
    'Mask',                     mask,   ...
    'InitialConditions',        init,   ...
    'SamplesPerFrame',          samples);
pnSeq1 = pnSequence1();

pnSequence2 = comm.PNSequence(...
    'Polynomial',               poly2,	...
    'Mask',                     mask,   ...
    'InitialConditions',        init,   ...
    'SamplesPerFrame',          samples);
pnSeq2 = pnSequence2();

goldSequence = comm.GoldSequence(...
    'FirstPolynomial',          poly1,	...
    'SecondPolynomial',         poly2,	...
    'FirstInitialConditions',   init,   ...
    'SecondInitialConditions',  init,   ...
    'Index',                    2,     ...
    'SamplesPerFrame',          samples);
goldSeq = goldSequence();

[all(goldSeq == pnSeq1),...  % goldSequence : Index = -2
all(goldSeq == pnSeq2),...  % goldSequence : Index = -1
all(goldSeq == xor(pnSeq1,pnSeq2))]  % goldSequence : Index = 0

[goldSeq, xor(pnSeq1, circshift(pnSeq2,-2))]